name: Post Build Action

run-name: 'Post Build Action -- ${{github.event.workflow_run.head_branch}}'

on:
   workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed

permissions:
  contents: write 
        
jobs:
  post-build:
    name: Post Build Actions
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'ikmdev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{github.event.workflow_run.head_repository.full_name}}
          ref: ${{github.event.workflow_run.head_branch}}
          fetch-depth: 0

      - name: Print Before GH Variable Test
        run: echo ${{vars.TEST_PROPERTY}}
          
      - name: IKMDEV Post Build Action
        id: ikmdev_post_build
        uses: ikmdev/maven-post-build-action@main
        with:
            nexus_repo_password: ${{secrets.EC2_NEXUS_PASSWORD}}
            branch_name: ${{github.event.workflow_run.head_branch}}
            github_token: ${{secrets.GITHUB_TOKEN}}
            ossrh_username: ${{secrets.OSSRH_TOKEN_USER}}
            ossrh_token: ${{secrets.OSSRH_TOKEN_PASS}}
            gpg_key: ${{secrets.GPG_KEY}}
            gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
            sonarcloud_token: ${{ secrets.SONAR_TOKEN }}

  # repository-dispatch:
  #      name: Repository Dispatch
  #     #  needs: post-build
  #     #  if: needs.post-build.outputs.IS_TAG == 'true'
  #      runs-on: ubuntu-24.04
  #      strategy:
  #       matrix:
  #         repos: [data-properties-test]
  #      steps:
  #       - name: Trigger Repository Dispatch
  #         run: |
  #           curl -X POST \
  #           -H "Accept: application/vnd.github.v3+json" \
  #           -H "Authorization: token ${{secrets.IKMDEVOPS_PAT_TOKEN}}" \
  #           https://api.github.com/repos/ikmdev/${{matrix.repos}}/dispatches \
  #           -d '{"event_type":"tinkar-trigger","client_payload":{"version":"1.1.0"}}'
