name: "SemVer Release Workflow"

run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"

# Trigger workflow manually
on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: "(Optional) Custom Release Version"
        required: false
      version_type:
        description: 'Development version type to increment'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

env:
  BRANCH_NAME: ${{ github.ref_name }}
  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Verify Branch
        if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
        run: |
          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only."
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

      - name: Shared Release Action
        uses: ikmdev/maven-semver-release-action@gitflow-plugin-test
        with:
          version_type: ${{ github.event.inputs.version_type }}
          github_token: ${{secrets.GITHUB_TOKEN}}
          release_version: ${{ github.event.inputs.release_version }}

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: ikmdev/demo-java-maven
          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

      - name: Update File With Latest TAG
        run: |
          cd .github/workflows
          git pull -p;
          LATEST-TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          sed -i '/-- SELECT --/a\          - $LATEST-TAG' generate-pipeline-test.yaml
          git commit -am"Updated Tag"
          git push
          
